name: aaaaSignin
author: FloodLin
description: 'AliyunDrive signin automatically'

inputs:
  GP_TOKEN:
    description: 'Github personal access token'
    required: false
    default: ''

  PUSHPLUS_TOKEN: 
    description: 'Pushplus'
    required: false
    default: ''

  Mobile_No: 
    description: 'Mobile'
    required: false
    default: ''
  province_Name:
    description: 'province'
    required: false
    default: ''  
  city_Name: 
    description: 'City'
    required: false
    default: ''  
  ID_TOKEN: 
    description: 'ID token'
    required: false
    default: ''          
  user_Id: 
     description: 'user id'
    required: false
    default: ''         
  lat: 
    description: 'lat'
    required: false
    default: ''          
  lng: 
    description: 'lng'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - id: version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: FloodLin/test
        excludes: prerelease, draft
        token: ${{ inputs.GP_TOKEN }}
    - name: Download
      shell: bash
      run: |
        wget https://github.com/FloodLin/test/archive/refs/tags/${{ steps.version.outputs.release }}.zip -O release.zip
        rm -rf release
        unzip release.zip -d release
        rm release.zip
    - name: Run
      shell: bash
      run: |
        cd release
        cd $(ls -dt */|head -1 )
        pip install -r requirements.txt
        python main.py -a
      env:
        PUSHPLUS_TOKEN: ${{ inputs.PUSHPLUS_TOKEN }}
          Mobile_No: ${{ inputs.Mobile_No }}
          province_Name: ${{ inputs.province_Name }}
          city_Name: ${{ inputs.city_Name }}
          ID_TOKEN: ${{ inputs.ID_TOKEN }}
          user_Id: ${{ inputs.user_Id }}
          lat: ${{ inputs.lat }}
          lng: ${{ inputs.lng }}
          GP_TOKEN: ${{ inputs.GP_TOKEN }}

branding:
    icon: 'check-circle'
    color: 'orange'
