name: aaaaSignin

on:
  schedule:
   # 每天国际时间 17:20 运行一次, 中国时间 01:20
    - cron: '21 17 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - id: version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: FloodLin/test
          excludes: prerelease, draft
          token: ${{ secrets.GP_TOKEN }}
      - name: Download
      
      shell: bash
      run: |
        wget https://github.com/FloodLin/test/archive/refs/tags/${{ steps.version.outputs.release }}.zip -O release.zip
        rm -rf release
        unzip release.zip -d release
        rm release.zip
    - name: Run
      shell: bash
      run: |
        cd release
        cd $(ls -dt */|head -1 )
        pip install -r requirements.txt
        python main.py -a
